export const categories = [
  {
    category: "General Discussions",
    id: 1,
    pic: "/files/Forum-Pictures/discussions.jpg",
    info: "Talk about anything you want.",
  },
  {
    category: "Music",
    id: 2,
    pic: "/files/Forum-Pictures/music.jpg",
    info: "Enjoy music with others.",
  },
  {
    category: "Hobbies",
    id: 3,
    pic: "/files/Forum-Pictures/hobbies.jpg",
    info: "Share and discover hobbies.",
  },
  {
    category: "Video Games",
    id: 4,
    pic: "/files/Forum-Pictures/video-games.jpg",
    info: "For the passion of gamers.",
  },
  {
    category: "Art",
    id: 5,
    pic: "/files/Forum-Pictures/art.jpg",
    info: "Share your creations with the world.",
  },
];
export const mockThreads = [
  {
    categoryID: 1,
    threadID: 1,
    author: "John1",
    threadName: "test",
    content: "Hello World!, from John.",
    views: 0,
    comments: 0,
  },
  {
    categoryID: 1,
    threadID: 2,
    author: "Jane1",
    threadName: "test",
    content: "Hello World! from Jane.",
    views: 0,
    comments: 0,
  },
  {
    categoryID: 2,
    threadID: 3,
    author: "John1",
    threadName: "test",
    content: "Hello Musicians!",
    views: 0,
    comments: 0,
  },
  {
    categoryID: 3,
    threadID: 4,
    author: "Jane1",
    threadName: "test",
    content: "Hello Hobbyists!",
    views: 0,
    comments: 0,
  },
  {
    categoryID: 4,
    threadID: 5,
    author: "John1",
    threadName: "test",
    content: "Hello Gamers!",
    views: 0,
    comments: 0,
  },
  {
    categoryID: 5,
    threadID: 6,
    author: "John1",
    threadName: "test",
    content: "Hello Artists!",
    views: 0,
    comments: 0,
  },
];
export const mockComments = [
  {
    threadID: 1,
    commentID: 1,
    author: "Jane1",
    comment: "Awesome!",
  },
  {
    threadID: 2,
    commentID: 2,
    author: "John1",
    comment: "Amazing!",
  },
  {
    threadID: 2,
    commentID: 3,
    author: "Jane1",
    comment: "Thanks!!",
  },
  {
    threadID: 3,
    commentID: 4,
    author: "Jane1",
    comment: "Hi! Musicians are awesome!",
  },
  {
    threadID: 4,
    commentID: 5,
    author: "John1",
    comment: "I have many hobbies!!",
  },
  {
    threadID: 5,
    commentID: 6,
    author: "Jane1",
    comment: "Games are fun.",
  },
  {
    threadID: 6,
    commentID: 7,
    author: "Jane1",
    comment: "S>ART @@@@@@@@@@@@@@@@@@",
  },
];
