export const categories = [
  {
    category: "General Discussions",
    id: 1,
    pic: "/files/Forum-Pictures/discussions.jpg",
    info: "Talk about anything you want.",
  },
  {
    category: "Music",
    id: 2,
    pic: "/files/Forum-Pictures/music.jpg",
    info: "Enjoy music with others.",
  },
  {
    category: "Hobbies",
    id: 3,
    pic: "/files/Forum-Pictures/hobbies.jpg",
    info: "Share and discover hobbies.",
  },
  {
    category: "Video Games",
    id: 4,
    pic: "/files/Forum-Pictures/video-games.jpg",
    info: "For the passion of gamers.",
  },
  {
    category: "Art",
    id: 5,
    pic: "/files/Forum-Pictures/art.jpg",
    info: "Share your creations with the world.",
  },
];
export const mockThreads = [
  {
    categoryID: 1,
    threadID: 1,
    author: "John1",
    threadName: "test",
    content: "Hello World!, from John.",
    views: 1,
    comments: 1,
    time: "16 / 04 / 2022, 14: 22",
  },
  {
    categoryID: 1,
    threadID: 2,
    author: "Jane1",
    threadName: "test",
    content: "Hello World! from Jane.",
    views: 2,
    comments: 2,
    time: "16 / 04 / 2022, 14: 22",
  },
  {
    categoryID: 2,
    threadID: 3,
    author: "John1",
    threadName: "test",
    content: "Hello Musicians!",
    views: 0,
    comments: 0,
    time: "16 / 04 / 2022, 14: 22",
  },
  {
    categoryID: 3,
    threadID: 4,
    author: "Jane1",
    threadName: "test",
    content: "Hello Hobbyists!",
    views: 1,
    comments: 1,
    time: "16 / 04 / 2022, 14: 22",
  },
  {
    categoryID: 4,
    threadID: 5,
    author: "John1",
    threadName: "test",
    content: "Hello Gamers!",
    views: 1,
    comments: 1,
    time: "16 / 04 / 2022, 14: 22",
  },
  {
    categoryID: 5,
    threadID: 6,
    author: "John1",
    threadName: "test",
    content: "Hello Artists!",
    views: 1,
    comments: 1,
    time: "16 / 04 / 2022, 14: 22",
  },
];
export const mockComments = [
  {
    threadID: 1,
    commentID: 1,
    author: "Jane1",
    comment: "Awesome!",
    time: "16 / 04 / 2022, 14: 22",
    editted: false,
  },
  {
    threadID: 2,
    commentID: 2,
    author: "John1",
    comment: "Amazing!",
    time: "16 / 04 / 2022, 14: 22",
    editted: false,
  },
  {
    threadID: 2,
    commentID: 3,
    author: "Jane1",
    comment: "Thanks!!",
    time: "16 / 04 / 2022, 14: 22",
    editted: false,
  },
  {
    threadID: 3,
    commentID: 4,
    author: "Jane1",
    comment: "Hi! Musicians are awesome!",
    time: "16 / 04 / 2022, 14: 22",
    editted: false,
  },
  {
    threadID: 4,
    commentID: 5,
    author: "John1",
    comment: "I have many hobbies!!",
    time: "16 / 04 / 2022, 14: 22",
    editted: false,
  },
  {
    threadID: 5,
    commentID: 6,
    author: "Jane1",
    comment: "Games are fun.",
    time: "16 / 04 / 2022, 14: 22",
    editted: false,
  },
  {
    threadID: 6,
    commentID: 7,
    author: "Jane1",
    comment: "S>ART @@@@@@@@@@@@@@@@@@",
    time: "16 / 04 / 2022, 14: 22",
    editted: false,
  },
];
export const banData = [
  {
    userID: 0,
    ban: false,
    reason: null,
  },
  {
    userID: 1,
    ban: false,
    reason: null,
  },
  {
    userID: 2,
    ban: false,
    reason: null,
  },
  {
    userID: 3,
    ban: true,
    reason: "profanity",
  },
];
export const mockPms = [
  {
    senderID: 0,
    recipientID: 1,
    title: "A message from the Administrator",
    content: "Hello, John1.",
    read: false,
    time: "16 / 04 / 2022, 14: 22",
    pmID: 0,
  },
  {
    senderID: 0,
    recipientID: 2,
    title: "A message from the Administrator",
    content: "Hello, jane1.",
    read: false,
    time: "16 / 04 / 2022, 14: 22",
    pmID: 1,
  },
  {
    senderID: 0,
    recipientID: 3,
    title: "A message from the Administrator",
    content: "Hello, Banned.",
    read: false,
    time: "16 / 04 / 2022, 14: 22",
    pmID: 2,
  },
];
